# Generated by Django 5.0.1 on 2024-02-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
