# Generated by Django 5.0.1 on 2024-02-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='items',
            name='prdt',
        ),
        migrations.DeleteModel(
            name='cartlist',
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
